# Generated by Django 5.0.4 on 2024-05-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='aceptada',
            new_name='estado',
        ),
    ]
