# Generated by Django 5.0.4 on 2024-05-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0002_rename_aceptada_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='mensaje',
            field=models.TextField(default='Hola, me gusta su propiedad, me gustaría arrendarla.'),
        ),
    ]
