# Generated by Django 5.0.4 on 2024-10-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPages', '0002_alter_comuna_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendador',
            name='usuario_ptr',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='arrendador',
            field=models.ForeignKey(limit_choices_to={'es_arrendador': True}, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='webPages.tipodeinmueble', to_field='nombre'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='comuna',
            constraint=models.UniqueConstraint(fields=('nombre', 'region'), name='unique_nombre_region'),
        ),
        migrations.DeleteModel(
            name='Arrendador',
        ),
        migrations.CreateModel(
            name='Arrendador',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webPages.usuario',),
        ),
    ]
