# Generated by Django 5.0.4 on 2024-10-03 21:30

import webPages.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webPages", "0003_remove_arrendador_usuario_ptr_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Arrendatario",
        ),
        migrations.CreateModel(
            name="Arrendatario",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("webPages.usuario",),
            managers=[
                ("objects", webPages.models.CustomUserManager()),
            ],
        ),
    ]
