# Generated by Django 5.0.4 on 2024-10-03 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("webPages", "0004_delete_arrendatario_arrendatario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arrendador",
            options={
                "verbose_name": "arrendador",
                "verbose_name_plural": "arrendadores",
            },
        ),
        migrations.AlterModelOptions(
            name="arrendatario",
            options={
                "verbose_name": "arrendatario",
                "verbose_name_plural": "arrendatarios",
            },
        ),
        migrations.AlterModelOptions(
            name="comuna",
            options={"verbose_name": "comuna", "verbose_name_plural": "comunas"},
        ),
        migrations.AlterModelOptions(
            name="datos",
            options={
                "verbose_name": "datos de usuario",
                "verbose_name_plural": "datos de usuarios",
            },
        ),
        migrations.AlterModelOptions(
            name="inmueble",
            options={"verbose_name": "inmueble", "verbose_name_plural": "inmuebles"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "región", "verbose_name_plural": "regiones"},
        ),
        migrations.AlterModelOptions(
            name="solicitud",
            options={"verbose_name": "solicitud", "verbose_name_plural": "solicitudes"},
        ),
        migrations.AlterModelOptions(
            name="tipodeinmueble",
            options={
                "verbose_name": "tipo de inmueble",
                "verbose_name_plural": "tipos de inmueble",
            },
        ),
        migrations.AlterField(
            model_name="comuna",
            name="nombre",
            field=models.CharField(
                help_text="Nombre de la comuna", max_length=100, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="comuna",
            name="region",
            field=models.ForeignKey(
                help_text="Región a la que pertenece la comuna",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunas",
                to="webPages.region",
                verbose_name="Región",
            ),
        ),
        migrations.AlterField(
            model_name="datos",
            name="direccion",
            field=models.CharField(
                default="",
                help_text="Dirección del usuario",
                max_length=100,
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="datos",
            name="email",
            field=models.EmailField(
                help_text="Correo electrónico de contacto",
                max_length=254,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="datos",
            name="telefono",
            field=models.CharField(
                help_text="Número de teléfono del usuario",
                max_length=15,
                verbose_name="Teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="datos",
            name="usuario",
            field=models.OneToOneField(
                help_text="Usuario asociado a estos datos",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                help_text="Usuario arrendador que publica el inmueble",
                limit_choices_to={"es_arrendador": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inmuebles",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
                verbose_name="Arrendador",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="cantidad_banos",
            field=models.IntegerField(
                default=1, help_text="Número de baños", verbose_name="Cantidad de baños"
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="cantidad_estacionamientos",
            field=models.IntegerField(
                default=1,
                help_text="Número de estacionamientos disponibles",
                verbose_name="Cantidad de estacionamientos",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="cantidad_habitaciones",
            field=models.IntegerField(
                default=1,
                help_text="Número de habitaciones",
                verbose_name="Cantidad de habitaciones",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="comuna",
            field=models.ForeignKey(
                help_text="Comuna donde se ubica el inmueble",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inmuebles",
                to="webPages.comuna",
                verbose_name="Comuna",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="descripcion",
            field=models.TextField(
                help_text="Descripción detallada del inmueble",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="direccion",
            field=models.CharField(
                help_text="Dirección del inmueble",
                max_length=100,
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="disponible",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el inmueble está disponible para arrendar",
                verbose_name="Disponible",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="fecha_actualizacion",
            field=models.DateField(
                auto_now=True,
                help_text="Fecha de la última actualización",
                verbose_name="Fecha de actualización",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="fecha_publicacion",
            field=models.DateField(
                auto_now_add=True,
                help_text="Fecha en que se publicó el inmueble",
                verbose_name="Fecha de publicación",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="imagen",
            field=models.ImageField(
                help_text="Imagen principal del inmueble",
                upload_to="inmuebles",
                verbose_name="Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="nombre",
            field=models.CharField(
                help_text="Nombre o título del inmueble",
                max_length=50,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="precio_arriendo",
            field=models.IntegerField(
                help_text="Precio mensual de arriendo",
                verbose_name="Precio de arriendo",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="superficie_construida",
            field=models.FloatField(
                help_text="Superficie construida en metros cuadrados",
                verbose_name="Superficie construida",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="superficie_total",
            field=models.FloatField(
                help_text="Superficie total del terreno en metros cuadrados",
                verbose_name="Superficie total",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="tipo_de_inmueble",
            field=models.ForeignKey(
                help_text="Tipo de inmueble (casa, departamento, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inmuebles",
                to="webPages.tipodeinmueble",
                to_field="nombre",
                verbose_name="Tipo de inmueble",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="nombre",
            field=models.CharField(
                help_text="Nombre de la región",
                max_length=100,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="arrendatario",
            field=models.ForeignKey(
                help_text="Arrendatario que realiza la solicitud",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to="webPages.arrendatario",
                verbose_name="Arrendatario",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                help_text="Estado actual de la solicitud",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_aceptacion",
            field=models.DateField(
                help_text="Fecha en que se aceptó la solicitud",
                null=True,
                verbose_name="Fecha de aceptación",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_rechazo",
            field=models.DateField(
                help_text="Fecha en que se rechazó la solicitud",
                null=True,
                verbose_name="Fecha de rechazo",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="fecha_solicitud",
            field=models.DateField(
                auto_now_add=True,
                help_text="Fecha en que se realizó la solicitud",
                verbose_name="Fecha de solicitud",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="inmueble",
            field=models.ForeignKey(
                help_text="Inmueble asociado a esta solicitud",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to="webPages.inmueble",
                verbose_name="Inmueble",
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="mensaje",
            field=models.TextField(
                default="Hola, me gusta su propiedad, me gustaría arrendarla.",
                help_text="Mensaje del arrendatario al arrendador",
                verbose_name="Mensaje",
            ),
        ),
        migrations.AlterField(
            model_name="tipodeinmueble",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del tipo de inmueble",
                max_length=100,
                unique=True,
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="apellido",
            field=models.CharField(
                help_text="Apellido del usuario", max_length=50, verbose_name="Apellido"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                help_text="Dirección de correo electrónico del usuario",
                max_length=254,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="es_arrendador",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario es un arrendador",
                verbose_name="Es arrendador",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos otorgados a cada uno de sus grupos.",
                related_name="usuario_set",
                related_query_name="usuario",
                to="auth.group",
                verbose_name="grupos",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del usuario", max_length=50, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rut",
            field=models.CharField(
                help_text="RUT del usuario (formato: 12345678-9)",
                max_length=9,
                primary_key=True,
                serialize=False,
                verbose_name="RUT",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permisos específicos para este usuario.",
                related_name="usuario_set",
                related_query_name="usuario",
                to="auth.permission",
                verbose_name="permisos de usuario",
            ),
        ),
    ]
