# Generated by Django 5.0.4 on 2024-10-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webPages",
            "0006_remove_usuario_date_joined_remove_usuario_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inmueble",
            name="imagen",
        ),
        migrations.AddField(
            model_name="inmueble",
            name="imagen_url",
            field=models.URLField(
                default="https://via.placeholder.com/300x200.png?text=No+Image",
                help_text="URL de la imagen principal del inmueble en S3",
                max_length=1000,
                verbose_name="URL de la imagen",
            ),
        ),
    ]
